exclude: |
  (^backend/venv/)           # your Python venv
  |(^backend/alembic/)       # Alembic migrations
  |(^frontend/node_modules/) # if you ever run hooks there
  |(^\.git/)                 # git internals
  |(^frontend/\.next/)       # Next.js build files

repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: ^backend/alembic/
        additional_dependencies: [flake8]
        args: ["--max-line-length=88"]
