"""Really Initializing the Tables

Revision ID: 127ed0465812
Revises: 
Create Date: 2025-07-18 10:48:48.019072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127ed0465812'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.create_index(op.f('ix_stores_type'), 'stores', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty_in', sa.Integer(), nullable=False),
    sa.Column('qty_out', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'store_id', 'item_id', name='uix_inventory_store_item_date')
    )
    op.create_index(op.f('ix_inventories_item_id'), 'inventories', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventories_store_id'), 'inventories', ['store_id'], unique=False)
    op.drop_table('sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('sales_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('store_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('sales_qty', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sales_amount_inc_vat', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('vat_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_sales', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('margin', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('margin_percent', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f('ix_inventories_store_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_item_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_table('users')
    op.drop_index(op.f('ix_stores_type'), table_name='stores')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
