"""change qty_in, qty_out to db, pg for consistency

Revision ID: 37d8beba65eb
Revises: 74b5842b3503
Create Date: 2025-07-19 14:02:06.284046

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37d8beba65eb"
down_revision: Union[str, Sequence[str], None] = "74b5842b3503"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inventories", sa.Column("db", sa.Integer(), nullable=False))
    op.add_column("inventories", sa.Column("pg", sa.Integer(), nullable=False))
    op.drop_column("inventories", "qty_in")
    op.drop_column("inventories", "qty_out")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventories",
        sa.Column("qty_out", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "inventories",
        sa.Column("qty_in", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("inventories", "pg")
    op.drop_column("inventories", "db")
    # ### end Alembic commands ###
