"""Initial tables

Revision ID: 404e7315148e
Revises: 
Create Date: 2025-07-18 10:05:35.521841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404e7315148e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('sales_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('store_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('sales_qty', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sales_amount_inc_vat', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('vat_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_sales', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('margin', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('margin_percent', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
