"""Update User Model, add password and username

Revision ID: 4317b58e4ed2
Revises: 37d8beba65eb
Create Date: 2025-07-20 17:38:42.150644

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4317b58e4ed2"
down_revision: Union[str, Sequence[str], None] = "37d8beba65eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "password")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
