"""empty message

Revision ID: 5a0bc90746c8
Revises: 620b968aed1f
Create Date: 2025-08-07 22:50:58.381833

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a0bc90746c8"
down_revision: Union[str, Sequence[str], None] = "620b968aed1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inventories", sa.Column("waste", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_inventories_date"), "inventories", ["date"], unique=False)
    op.drop_column("inventories", "sm2")
    op.drop_column("inventories", "sm1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventories",
        sa.Column(
            "sm1",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "inventories",
        sa.Column(
            "sm2",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_inventories_date"), table_name="inventories")
    op.drop_column("inventories", "waste")
    # ### end Alembic commands ###
