"""update sm columns

Revision ID: 620b968aed1f
Revises: c3342da07071
Create Date: 2025-07-22 08:43:45.248575

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "620b968aed1f"
down_revision: Union[str, Sequence[str], None] = "c3342da07071"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventories",
        sa.Column("sm1", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "inventories",
        sa.Column("sm2", sa.Integer(), server_default="0", nullable=False),
    )
    op.drop_column("inventories", "sm")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventories",
        sa.Column(
            "sm",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("inventories", "sm2")
    op.drop_column("inventories", "sm1")
    # ### end Alembic commands ###
