"""add sm column

Revision ID: c3342da07071
Revises: d166167472e4
Create Date: 2025-07-21 20:45:13.081390

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3342da07071"
down_revision: Union[str, Sequence[str], None] = "d166167472e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventories", sa.Column("sm", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventories", "sm")
    # ### end Alembic commands ###
