"""fix created_at and updated_at defaults on tokens

Revision ID: ee2b0589c139
Revises: 185d2b575554
Create Date: 2025-07-20 18:50:53.172471

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee2b0589c139"
down_revision: Union[str, Sequence[str], None] = "185d2b575554"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
