"""add refresh_tokens table

Revision ID: f6cc31b05f4e
Revises: 4317b58e4ed2
Create Date: 2025-07-20 18:25:37.458444

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6cc31b05f4e"
down_revision: Union[str, Sequence[str], None] = "4317b58e4ed2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
