"""set server defaults

Revision ID: fe6d2d16f136
Revises: 5a0bc90746c8
Create Date: 2025-09-17 10:42:49.016785

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe6d2d16f136"
down_revision: Union[str, Sequence[str], None] = "5a0bc90746c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventories",
        sa.Column("rem", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "inventories",
        sa.Column("b0_end", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "inventories",
        sa.Column("b1_end", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.drop_index(op.f("ix_inventories_date"), table_name="inventories")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_inventories_date"), "inventories", ["date"], unique=False)
    op.drop_column("inventories", "b1_end")
    op.drop_column("inventories", "b0_end")
    op.drop_column("inventories", "rem")
    # ### end Alembic commands ###
